services:
  bundle_service:
    container_name: bundle_service
    image: dt/bundle_service:latest
    ports:
      - '8080:8080'
    network_mode: bundle_service_network
    volumes: 
      - '/home/sushant/bundleservice/logs:/var/logs'
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: bundle_service
      MYSQL_PASS: password
      REDIS_HOST: redis 
